# Generated by Django 3.0.4 on 2022-02-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refund_policy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256)),
                ('answer', models.TextField()),
            ],
        ),
    ]
