# Generated by Django 3.0.4 on 2022-02-23 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refund_policy', '0002_deadline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deadline',
        ),
    ]
