# Generated by Django 3.0.4 on 2022-03-17 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('postal_code', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.Address'),
        ),
    ]
