# Generated by Django 3.0.4 on 2022-03-20 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20220320_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='default',
        ),
    ]
