# Generated by Django 3.0.4 on 2021-11-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20211128_1317'),
        ('contacts', '0004_userprofile_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='orders',
            field=models.ManyToManyField(blank=True, to='jobs.Order'),
        ),
    ]
