# Generated by Django 3.0.4 on 2021-11-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='education_level',
            new_name='academic_level',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='title',
            new_name='days',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='discipline',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='order',
            name='deadline',
        ),
        migrations.AddField(
            model_name='order',
            name='istructions',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='number_of_pages',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
