# Generated by Django 3.0.4 on 2021-11-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20211126_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='currentorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderfile',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_cancelled',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_completed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_inprogress',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('IP', 'inprogress'), ('CP', 'Completed'), ('CN', 'Cancelled')], max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='CancelledOrder',
        ),
        migrations.DeleteModel(
            name='CompletedOrder',
        ),
        migrations.DeleteModel(
            name='CurrentOrder',
        ),
        migrations.DeleteModel(
            name='OrderFile',
        ),
    ]
