# Generated by Django 3.0.4 on 2021-11-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20211128_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refrence_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
