# Generated by Django 3.0.4 on 2021-12-01 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_order_refrence_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='refrence_code',
            new_name='reference_code',
        ),
    ]
