# Generated by Django 3.0.4 on 2021-12-11 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20211211_1158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcdemicLevel',
            new_name='AcademicLevel',
        ),
    ]
