# Generated by Django 3.0.4 on 2021-12-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20211226_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='files',
            field=models.ManyToManyField(blank=True, to='jobs.OrderFile'),
        ),
    ]
