# Generated by Django 3.0.4 on 2022-01-19 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20211226_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='files',
        ),
        migrations.DeleteModel(
            name='OrderFile',
        ),
    ]
