# Generated by Django 3.0.4 on 2022-01-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_assignmentfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentfile',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
