# Generated by Django 3.0.4 on 2022-01-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_auto_20220119_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='assignment_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
