# Generated by Django 3.0.4 on 2022-01-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_auto_20220119_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_complete',
            field=models.CharField(blank=True, choices=[('T', 'True'), ('F', 'False')], max_length=1, null=True),
        ),
    ]
