# Generated by Django 3.0.4 on 2022-01-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_auto_20220129_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_complete',
            field=models.CharField(blank=True, choices=[('T', 'True'), ('F', 'False')], default='F', max_length=1, null=True),
        ),
    ]
