# Generated by Django 3.0.4 on 2022-03-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_auto_20220301_0528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='user',
        ),
        migrations.AddField(
            model_name='writer',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
