# Generated by Django 3.0.4 on 2022-03-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_auto_20220302_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfile',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
