# Generated by Django 3.0.4 on 2022-03-20 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
