# Generated by Django 3.0.4 on 2021-10-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_edits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
