# Generated by Django 3.0.4 on 2021-11-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_edits', '0002_auto_20211004_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='howweworktext',
            name='thumb',
        ),
    ]
