# Generated by Django 3.0.4 on 2021-11-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_edits', '0003_remove_howweworktext_thumb'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowWeWorkCheckListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
