# Generated by Django 3.0.4 on 2021-11-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_edits', '0005_auto_20211118_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='name',
            field=models.CharField(default='privacy policy', max_length=50),
        ),
    ]
