# Generated by Django 3.0.4 on 2021-12-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_edits', '0007_academiclevel_day_format_page_spacing_subject_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcademicLevel',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Format',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='Spacing',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
