# Generated by Django 3.0.4 on 2022-02-14 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_edits', '0011_howweworktext_thumbnail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivacyPolicy',
        ),
        migrations.DeleteModel(
            name='RefundPolicy',
        ),
    ]
