# Generated by Django 3.0.4 on 2022-02-23 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_edits', '0012_auto_20220214_0450'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HowWeWorkCheckListItem',
        ),
    ]
