# Generated by Django 3.0.4 on 2022-02-23 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_edits', '0013_delete_howweworkchecklistitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhatsappNumber',
        ),
    ]
