# Generated by Django 3.0.4 on 2022-03-02 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_edits', '0014_delete_whatsappnumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HowWeWorkText',
        ),
    ]
