# Generated by Django 3.0.4 on 2022-02-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentwritingservice',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='contentwritingservice',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='dissertationandthesishelp',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='proofreadingservice',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=None),
        ),
    ]
