# Generated by Django 3.0.4 on 2022-02-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20220214_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentwritingservice',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='contentwritingservice',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='dissertationandthesishelp',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='proofreadingservice',
            name='thumbnail',
        ),
    ]
