# Generated by Django 4.0.3 on 2022-04-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20220214_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentwritingservice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contentwritingservice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dissertationandthesishelp',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proofreadingservice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
