# Generated by Django 3.0.4 on 2022-02-19 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('how_we_work', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faq',
        ),
        migrations.DeleteModel(
            name='HowWeWorkCheckList',
        ),
    ]
