# Generated by Django 3.0.4 on 2022-02-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('how_we_work', '0002_auto_20220219_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowWeWorkCheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
