# Generated by Django 4.0.3 on 2022-04-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('how_we_work', '0004_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='howwework',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='howweworkchecklist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
